FC=wfl386

all: life.exe show.exe genblank.exe genrand.exe tidy .SYMBOLIC

life.exe: life.obj period2d.obj pbmtools.obj ouchow.obj drawow.obj
	$(FC) period2d.obj pbmtools.obj ouchow.obj drawow.obj life.obj

show.exe: show.obj period2d.obj pbmtools.obj ouchow.obj drawow.obj
	$(FC) period2d.obj pbmtools.obj ouchow.obj drawow.obj show.obj

genblank.exe: genblank.obj period2d.obj pbmtools.obj ouchow.obj
	$(FC) period2d.obj pbmtools.obj ouchow.obj genblank.obj

genrand.exe: genrand.obj period2d.obj pbmtools.obj ouchow.obj
	$(FC) period2d.obj pbmtools.obj ouchow.obj genrand.obj

genblank.obj: genblank.f makefile
	$(FC) -c genblank.f

genrand.obj: genrand.f makefile
	$(FC) -c genrand.f

show.obj: show.f makefile
	$(FC) -c show.f

life.obj: life.f makefile
	$(FC) -c life.f

ouchow.obj: ouchow.f makefile
	$(FC) -c ouchow.f

drawow.obj: drawow.f makefile
	$(FC) -c drawow.f

period2d.obj: period2d.f makefile
	$(FC) -c period2d.f

pbmtools.obj: pbmtools.f makefile
	$(FC) -c pbmtools.f


clean: .SYMBOLIC
	del *.obj
	del *.exe
	del *.err
	del out.pbm

tidy: .SYMBOLIC
	del *.obj
	del *.err

